### ISSUE TITLE
Mysql is not working

### ISSUE THREAD

**Issue by mosamlife** [sitepilot/runtime#4]
Hello,

Mysql is not working inside the container. Am I missing something?

**Comment by nbejansen** [comment]
Hello @mosamlife, 

MySQL isn't installed in the container. The image only contains Nginx and PHP-FPM. Spin up an additional container ([MySQL ](https://hub.docker.com/_/mysql )/ [MariaDB](https://hub.docker.com/_/mariadb)) for the database.

Best regards,
Nick Jansen
